### This should return JSON content.

GET http://localhost:3000/DummyJson?name=maret
Accept: application/json

### This should return HTML content.

GET http://localhost:3000/DummyHtml?name=nazmul
Accept: application/html

### This should return "No route found!" (text content).

GET http://localhost:3000/
Accept: text/plain

### This should echo the query params (text content).

GET http://localhost:3000/Echo?location=mountain-view&time=evening
Accept: text/plain

